version: '3.8'

services:
  backend:
    build:
      context: ./SERVER
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./SERVER:/app
    depends_on:
      - mongo

  frontend:
    build:
      context: ./ONLINE_PG_RESERVATION_SYSTEM
    ports:
      - "80:80"
    depends_on:
      - SERVER

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
